insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (1, 'Tabatha', 'Caverhill', 'Electrician', '2025-11-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (2, 'Catina', 'Derrell', 'Cleaner', '2025-07-16');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (3, 'Vivianne', 'Jobling', 'Equipment Specialist', '2025-10-12');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (4, 'Merrie', 'Medd', 'Maintenance Technician', '2025-07-10');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (5, 'Silvano', 'Commins', 'Cleaner', '2025-11-14');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (6, 'Margret', 'Tabord', 'Facility Coordinator', '2026-01-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (7, 'Lulita', 'Phipard-Shears', 'Maintenance Technician', '2026-02-10');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (8, 'Kaleb', 'Goodbanne', 'Maintenance Technician', '2025-07-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (9, 'Blondell', 'Anneslie', 'Equipment Specialist', '2025-09-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (10, 'Elfreda', 'Whordley', 'Facility Coordinator', '2026-01-09');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (11, 'Michaelina', 'Cockran', 'Operations Manager', '2025-12-28');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (12, 'Barnard', 'Fritschmann', 'Cleaner', '2025-12-22');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (13, 'Rickie', 'Mushart', 'Equipment Specialist', '2025-10-21');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (14, 'Cobby', 'Laux', 'Cleaner', '2026-02-18');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (15, 'Berti', 'Harlowe', 'Electrician', '2025-08-17');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (16, 'Nertie', 'Welham', 'Equipment Specialist', '2025-07-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (17, 'Marna', 'McMeyler', 'Operations Manager', '2025-09-05');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (18, 'Emmaline', 'Cheevers', 'Cleaner', '2026-02-16');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (19, 'Natalya', 'Lundberg', 'Electrician', '2025-04-20');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (20, 'Jaclyn', 'Straine', 'Operations Manager', '2025-09-04');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (21, 'Mirella', 'Garron', 'Operations Manager', '2025-05-17');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (22, 'Celestia', 'Dracey', 'Facility Coordinator', '2025-04-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (23, 'Dall', 'Prine', 'Equipment Specialist', '2025-05-02');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (24, 'Rodger', 'Yong', 'Electrician', '2025-10-16');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (25, 'Lari', 'Lening', 'Equipment Specialist', '2026-02-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (26, 'Darbie', 'Helin', 'Electrician', '2025-12-07');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (27, 'Dorena', 'Favey', 'Equipment Specialist', '2025-05-28');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (28, 'Kora', 'Kadar', 'Maintenance Technician', '2026-01-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (29, 'Aurlie', 'Fanning', 'Equipment Specialist', '2026-02-08');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (30, 'Lizbeth', 'Coppens', 'Maintenance Technician', '2026-01-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (31, 'Rene', 'Torritti', 'Maintenance Technician', '2025-12-14');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (32, 'Lorine', 'Murie', 'Operations Manager', '2026-02-26');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (33, 'Ilyssa', 'Chawner', 'Cleaner', '2025-05-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (34, 'Clarance', 'Bacop', 'Facility Coordinator', '2025-05-07');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (35, 'Angele', 'Bastow', 'Cleaner', '2025-06-10');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (36, 'Sawyer', 'McGinlay', 'Cleaner', '2025-11-14');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (37, 'Chrystal', 'Down', 'Cleaner', '2026-03-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (38, 'Stafford', 'Finey', 'Equipment Specialist', '2025-11-27');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (39, 'Durante', 'Glavis', 'Electrician', '2025-06-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (40, 'Sinclare', 'Cosely', 'Equipment Specialist', '2025-04-07');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (41, 'Towney', 'Behnecken', 'Operations Manager', '2025-07-16');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (42, 'Sorcha', 'Beggini', 'Operations Manager', '2025-11-22');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (43, 'Alleen', 'Cheers', 'Electrician', '2026-01-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (44, 'Claudelle', 'Garry', 'Electrician', '2025-10-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (45, 'Odette', 'Gratrix', 'Equipment Specialist', '2025-05-07');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (46, 'Tonie', 'Salla', 'Equipment Specialist', '2025-04-02');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (47, 'Shellysheldon', 'Adam', 'Cleaner', '2026-02-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (48, 'Margi', 'McComiskey', 'Maintenance Technician', '2025-09-12');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (49, 'Windham', 'Burberry', 'Electrician', '2025-11-23');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (50, 'Willie', 'Gerrelts', 'Maintenance Technician', '2025-09-27');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (51, 'Teddie', 'Antonias', 'Cleaner', '2025-03-31');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (52, 'Ellynn', 'Cutts', 'Equipment Specialist', '2025-05-05');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (53, 'Louisette', 'Tomkys', 'Maintenance Technician', '2025-08-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (54, 'Fax', 'Godfray', 'Operations Manager', '2026-02-09');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (55, 'Meggie', 'Gabites', 'Maintenance Technician', '2025-08-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (56, 'Laura', 'Wilde', 'Facility Coordinator', '2026-03-05');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (57, 'Lorie', 'Ateridge', 'Electrician', '2025-08-26');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (58, 'Valli', 'Jarnell', 'Operations Manager', '2026-02-10');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (59, 'Johna', 'Paskerful', 'Equipment Specialist', '2025-11-08');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (60, 'Dot', 'Parsisson', 'Cleaner', '2025-05-14');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (61, 'Charlotte', 'Dallinder', 'Electrician', '2026-02-21');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (62, 'Ogden', 'Blaschke', 'Operations Manager', '2025-08-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (63, 'Bertina', 'Lowdyane', 'Operations Manager', '2026-03-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (64, 'Imogen', 'Heino', 'Facility Coordinator', '2025-09-05');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (65, 'Rheba', 'Lancetter', 'Maintenance Technician', '2025-09-04');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (66, 'Bill', 'Aspall', 'Facility Coordinator', '2025-12-02');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (67, 'Riordan', 'Scyner', 'Operations Manager', '2025-06-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (68, 'May', 'Abilowitz', 'Maintenance Technician', '2026-03-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (69, 'Thelma', 'Vaggers', 'Cleaner', '2025-08-14');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (70, 'Conny', 'Gibbett', 'Facility Coordinator', '2025-08-04');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (71, 'Margaret', 'Argyle', 'Electrician', '2025-11-05');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (72, 'Patten', 'Lendon', 'Maintenance Technician', '2025-07-15');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (73, 'Bar', 'MacDearmid', 'Operations Manager', '2025-09-20');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (74, 'Darcy', 'Feldmesser', 'Electrician', '2025-12-08');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (75, 'Spense', 'Savell', 'Electrician', '2025-07-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (76, 'Maryanna', 'Gummary', 'Maintenance Technician', '2025-06-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (77, 'Marijo', 'D''Adda', 'Electrician', '2025-04-15');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (78, 'Saloma', 'Newbold', 'Electrician', '2025-04-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (79, 'Hobart', 'Bedboro', 'Cleaner', '2026-02-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (80, 'Tedmund', 'Wooster', 'Cleaner', '2025-10-17');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (81, 'Konstantine', 'Titterton', 'Operations Manager', '2025-09-27');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (82, 'Bonnibelle', 'Peniman', 'Operations Manager', '2026-02-26');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (83, 'Anselma', 'Ladbrook', 'Cleaner', '2025-10-26');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (84, 'Olvan', 'Cadore', 'Electrician', '2025-11-04');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (85, 'Torrie', 'Bindin', 'Equipment Specialist', '2025-08-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (86, 'Berke', 'Garretson', 'Equipment Specialist', '2025-11-13');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (87, 'Marga', 'Beeke', 'Facility Coordinator', '2026-02-18');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (88, 'Massimo', 'Claque', 'Facility Coordinator', '2026-03-05');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (89, 'Catharina', 'Romain', 'Maintenance Technician', '2025-09-27');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (90, 'Kaleena', 'Portt', 'Cleaner', '2025-08-05');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (91, 'Lind', 'Ungerechts', 'Maintenance Technician', '2025-06-12');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (92, 'Nadeen', 'Cauley', 'Electrician', '2025-07-10');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (93, 'Amalle', 'Andreopolos', 'Maintenance Technician', '2026-01-23');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (94, 'Mandie', 'Baumadier', 'Equipment Specialist', '2025-12-16');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (95, 'Leonerd', 'Lamb', 'Maintenance Technician', '2025-11-07');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (96, 'Linda', 'Stanmore', 'Facility Coordinator', '2025-05-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (97, 'Gratiana', 'Breming', 'Equipment Specialist', '2025-11-09');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (98, 'Edyth', 'Hrinchishin', 'Maintenance Technician', '2025-08-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (99, 'Andie', 'Rooke', 'Equipment Specialist', '2025-04-14');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (100, 'Tara', 'Overshott', 'Facility Coordinator', '2025-06-28');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (101, 'Paulita', 'Pavinese', 'Equipment Specialist', '2025-08-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (102, 'Hana', 'Gunby', 'Maintenance Technician', '2026-03-04');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (103, 'Alphonso', 'Franzonetti', 'Maintenance Technician', '2025-12-13');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (104, 'Georgette', 'Dymocke', 'Equipment Specialist', '2026-01-02');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (105, 'Pail', 'Gergolet', 'Equipment Specialist', '2026-01-23');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (106, 'Lari', 'Hellis', 'Electrician', '2025-05-16');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (107, 'Norean', 'Robet', 'Equipment Specialist', '2025-08-13');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (108, 'Abra', 'Sedgmond', 'Maintenance Technician', '2025-08-17');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (109, 'Bevon', 'Nijs', 'Facility Coordinator', '2025-11-18');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (110, 'Barn', 'Danielli', 'Cleaner', '2026-01-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (111, 'Matt', 'Ellcome', 'Equipment Specialist', '2025-07-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (112, 'Dixie', 'Trudgion', 'Cleaner', '2025-09-16');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (113, 'Karmen', 'Dimitrie', 'Cleaner', '2025-07-07');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (114, 'Bartlett', 'Caroli', 'Electrician', '2025-11-13');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (115, 'Marrissa', 'Pinwell', 'Operations Manager', '2025-08-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (116, 'Greggory', 'Richmond', 'Facility Coordinator', '2025-09-21');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (117, 'Gustave', 'Caslett', 'Maintenance Technician', '2025-12-31');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (118, 'Carmina', 'Jacmar', 'Electrician', '2025-09-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (119, 'Stavros', 'Holbury', 'Equipment Specialist', '2025-10-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (120, 'Nicky', 'Simonsen', 'Facility Coordinator', '2025-12-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (121, 'Daphene', 'Kubczak', 'Cleaner', '2026-01-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (122, 'Bartolemo', 'Ruckman', 'Maintenance Technician', '2025-05-12');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (123, 'Darn', 'Ingold', 'Electrician', '2026-01-30');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (124, 'Birgit', 'Drinkwater', 'Facility Coordinator', '2025-10-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (125, 'Sheilah', 'Cothey', 'Equipment Specialist', '2025-09-10');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (126, 'Stacee', 'Taffley', 'Operations Manager', '2025-09-13');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (127, 'Amanda', 'Stother', 'Maintenance Technician', '2025-10-31');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (128, 'Jeth', 'Fullager', 'Maintenance Technician', '2025-04-26');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (129, 'Willa', 'Carlisi', 'Cleaner', '2025-10-13');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (130, 'Robinett', 'Colleck', 'Electrician', '2025-10-22');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (131, 'Silvain', 'Danilewicz', 'Maintenance Technician', '2025-05-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (132, 'Araldo', 'Stansell', 'Cleaner', '2025-05-02');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (133, 'Sherye', 'Labbati', 'Maintenance Technician', '2025-10-31');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (134, 'Lorin', 'Skirrow', 'Facility Coordinator', '2026-03-10');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (135, 'Osgood', 'Fothergill', 'Cleaner', '2025-11-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (136, 'Hurlee', 'Warrilow', 'Facility Coordinator', '2025-07-12');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (137, 'Eveleen', 'Beaudry', 'Facility Coordinator', '2025-04-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (138, 'Dianna', 'Withrop', 'Equipment Specialist', '2025-07-17');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (139, 'Johnette', 'Greenlies', 'Facility Coordinator', '2025-07-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (140, 'Elvyn', 'Le Barre', 'Equipment Specialist', '2025-05-09');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (141, 'Charity', 'Blanchflower', 'Cleaner', '2025-11-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (142, 'Candy', 'Braunton', 'Operations Manager', '2025-11-18');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (143, 'Mercedes', 'Jellett', 'Facility Coordinator', '2025-07-07');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (144, 'Blondie', 'Moulder', 'Operations Manager', '2025-08-23');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (145, 'Yves', 'Boyfield', 'Maintenance Technician', '2025-12-26');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (146, 'Lorens', 'Mackriell', 'Maintenance Technician', '2026-01-20');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (147, 'Burl', 'Sim', 'Facility Coordinator', '2025-11-21');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (148, 'Eliza', 'Perot', 'Maintenance Technician', '2026-03-23');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (149, 'Patti', 'Skull', 'Equipment Specialist', '2025-05-15');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (150, 'Innis', 'Tribe', 'Maintenance Technician', '2025-09-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (151, 'Lib', 'Palek', 'Facility Coordinator', '2025-08-23');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (152, 'Shep', 'Eggerton', 'Equipment Specialist', '2025-09-18');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (153, 'Jasun', 'Hovert', 'Equipment Specialist', '2025-11-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (154, 'Regine', 'MacCulloch', 'Equipment Specialist', '2025-09-23');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (155, 'Shanna', 'Chatterton', 'Electrician', '2026-02-04');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (156, 'Evonne', 'Aveling', 'Cleaner', '2026-01-13');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (157, 'Teodoro', 'Bisson', 'Electrician', '2026-01-05');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (158, 'Bernie', 'Faircley', 'Equipment Specialist', '2026-02-13');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (159, 'Ellswerth', 'Wilkin', 'Cleaner', '2025-04-17');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (160, 'Valene', 'McVanamy', 'Cleaner', '2025-04-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (161, 'Zollie', 'Beardon', 'Equipment Specialist', '2025-05-21');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (162, 'Dulci', 'Domange', 'Electrician', '2025-10-08');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (163, 'Hillier', 'Brack', 'Cleaner', '2026-02-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (164, 'Brose', 'Tesseyman', 'Maintenance Technician', '2025-04-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (165, 'Frayda', 'Saffen', 'Equipment Specialist', '2025-07-16');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (166, 'Pepito', 'Dulake', 'Maintenance Technician', '2025-03-26');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (167, 'Leonore', 'Hissett', 'Operations Manager', '2025-05-21');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (168, 'Pinchas', 'Clement', 'Maintenance Technician', '2025-05-28');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (169, 'Verena', 'Emanueli', 'Facility Coordinator', '2026-03-02');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (170, 'Kaitlyn', 'Keeton', 'Equipment Specialist', '2025-10-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (171, 'Charyl', 'Zanetti', 'Maintenance Technician', '2025-08-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (172, 'Helga', 'Rillstone', 'Equipment Specialist', '2025-04-02');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (173, 'Thurston', 'Gratten', 'Cleaner', '2025-10-28');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (174, 'Brocky', 'Woloschin', 'Equipment Specialist', '2025-05-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (175, 'Norrie', 'Vannuccini', 'Electrician', '2026-03-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (176, 'Lee', 'Ferneley', 'Facility Coordinator', '2025-12-21');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (177, 'Keary', 'Haughton', 'Maintenance Technician', '2026-03-13');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (178, 'Magnum', 'Le Barr', 'Electrician', '2025-12-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (179, 'Belinda', 'Cardenosa', 'Facility Coordinator', '2026-02-10');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (180, 'Silvanus', 'Mathan', 'Operations Manager', '2025-11-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (181, 'Kimberli', 'Didsbury', 'Electrician', '2025-04-13');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (182, 'Richart', 'Holson', 'Cleaner', '2025-06-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (183, 'Angie', 'Jamot', 'Equipment Specialist', '2025-08-04');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (184, 'Junie', 'Kupisz', 'Operations Manager', '2026-02-12');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (185, 'Berna', 'O''Fihily', 'Maintenance Technician', '2025-05-28');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (186, 'Robert', 'Riddlesden', 'Electrician', '2025-11-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (187, 'Wendi', 'Kuhlen', 'Cleaner', '2025-12-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (188, 'Conan', 'Richings', 'Operations Manager', '2025-06-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (189, 'Giraud', 'Simukov', 'Electrician', '2025-09-15');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (190, 'Vern', 'Marquess', 'Equipment Specialist', '2025-04-21');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (191, 'Burnaby', 'Brewood', 'Maintenance Technician', '2025-08-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (192, 'Bethina', 'Cellier', 'Facility Coordinator', '2025-05-31');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (193, 'Helli', 'Denny', 'Maintenance Technician', '2026-02-12');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (194, 'Gerianne', 'Elwood', 'Facility Coordinator', '2026-01-14');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (195, 'Nowell', 'Cleaves', 'Equipment Specialist', '2026-01-04');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (196, 'Batsheva', 'Merigot', 'Cleaner', '2025-10-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (197, 'Jenilee', 'Burbury', 'Equipment Specialist', '2025-09-26');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (198, 'Yoshiko', 'Littleproud', 'Facility Coordinator', '2025-11-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (199, 'Alana', 'Moakson', 'Cleaner', '2026-02-21');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (200, 'Pierre', 'Archard', 'Cleaner', '2025-12-04');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (201, 'Peder', 'Trammel', 'Facility Coordinator', '2025-04-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (202, 'See', 'Snoden', 'Electrician', '2025-08-26');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (203, 'Martie', 'Hellsdon', 'Equipment Specialist', '2025-04-26');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (204, 'Ollie', 'Bushill', 'Facility Coordinator', '2026-03-14');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (205, 'Edythe', 'Grahamslaw', 'Maintenance Technician', '2025-05-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (206, 'Kerwin', 'Swettenham', 'Equipment Specialist', '2025-05-15');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (207, 'Blane', 'Cash', 'Electrician', '2025-11-09');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (208, 'Dori', 'Klimuk', 'Electrician', '2025-07-14');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (209, 'Marcelo', 'Burchatt', 'Cleaner', '2026-03-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (210, 'Thelma', 'Ungaretti', 'Operations Manager', '2025-04-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (211, 'Lissy', 'Trimming', 'Facility Coordinator', '2025-04-09');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (212, 'Albie', 'Terney', 'Cleaner', '2026-03-13');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (213, 'Harman', 'Celle', 'Cleaner', '2025-05-26');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (214, 'Mireielle', 'Naile', 'Facility Coordinator', '2026-03-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (215, 'Meara', 'O'' Meara', 'Maintenance Technician', '2025-03-30');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (216, 'Gert', 'Olney', 'Electrician', '2025-06-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (217, 'Gherardo', 'Knowles', 'Equipment Specialist', '2025-07-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (218, 'Durward', 'Engley', 'Operations Manager', '2026-02-02');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (219, 'Alanson', 'Ludlam', 'Facility Coordinator', '2025-12-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (220, 'Inessa', 'Orro', 'Facility Coordinator', '2025-10-21');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (221, 'Demott', 'Foden', 'Cleaner', '2026-01-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (222, 'Nari', 'Cay', 'Maintenance Technician', '2025-09-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (223, 'Rikki', 'Neaverson', 'Operations Manager', '2025-05-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (224, 'Sandie', 'Andrejevic', 'Equipment Specialist', '2025-05-16');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (225, 'Livvie', 'MacLachlan', 'Equipment Specialist', '2025-10-26');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (226, 'Eleonora', 'Saw', 'Operations Manager', '2025-07-22');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (227, 'Ethel', 'Klousner', 'Facility Coordinator', '2025-09-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (228, 'Gualterio', 'Stollberger', 'Maintenance Technician', '2025-08-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (229, 'Doug', 'Carbonell', 'Electrician', '2026-03-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (230, 'Sam', 'Ankers', 'Maintenance Technician', '2025-06-28');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (231, 'Kristi', 'Challice', 'Equipment Specialist', '2025-05-14');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (232, 'Enoch', 'Gladebeck', 'Equipment Specialist', '2025-09-20');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (233, 'Kirsten', 'Corroyer', 'Equipment Specialist', '2025-09-16');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (234, 'Karlotta', 'Brevetor', 'Operations Manager', '2025-05-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (235, 'Benson', 'Douche', 'Electrician', '2026-03-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (236, 'Elora', 'Boriston', 'Maintenance Technician', '2025-07-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (237, 'Netty', 'Cockayne', 'Equipment Specialist', '2025-12-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (238, 'Shem', 'Rosenvasser', 'Cleaner', '2025-10-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (239, 'Karleen', 'Chasson', 'Equipment Specialist', '2026-01-13');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (240, 'Stormi', 'Ebbutt', 'Electrician', '2025-04-28');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (241, 'Cliff', 'Buckle', 'Cleaner', '2025-12-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (242, 'Salomo', 'Youngman', 'Electrician', '2026-01-22');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (243, 'Bryna', 'Neads', 'Facility Coordinator', '2026-01-26');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (244, 'Wye', 'Pennings', 'Maintenance Technician', '2025-10-22');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (245, 'Gran', 'Cattrell', 'Maintenance Technician', '2026-03-18');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (246, 'Jules', 'Bruford', 'Facility Coordinator', '2025-08-20');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (247, 'Benedetta', 'Osant', 'Maintenance Technician', '2026-01-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (248, 'Lin', 'Phayre', 'Equipment Specialist', '2025-04-17');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (249, 'Gardiner', 'Bucher', 'Operations Manager', '2025-10-17');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (250, 'Hedvig', 'Meech', 'Cleaner', '2025-11-30');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (251, 'Dinny', 'King', 'Electrician', '2025-10-05');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (252, 'Caitrin', 'Cattanach', 'Electrician', '2025-07-28');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (253, 'Felizio', 'Elia', 'Maintenance Technician', '2025-11-13');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (254, 'Thorny', 'Moncreiffe', 'Cleaner', '2026-01-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (255, 'Wrennie', 'Beckhouse', 'Equipment Specialist', '2025-09-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (256, 'Shamus', 'Gurys', 'Operations Manager', '2025-07-05');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (257, 'Henriette', 'Rockwell', 'Facility Coordinator', '2025-03-31');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (258, 'Freemon', 'Pinnick', 'Electrician', '2025-05-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (259, 'Tallulah', 'Benet', 'Electrician', '2025-11-27');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (260, 'Quincy', 'Gertz', 'Maintenance Technician', '2025-09-10');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (261, 'Camellia', 'Heaford', 'Electrician', '2025-05-09');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (262, 'Elsa', 'Braidwood', 'Cleaner', '2025-06-16');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (263, 'Jim', 'Fiander', 'Operations Manager', '2025-04-17');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (264, 'Anita', 'MacWilliam', 'Maintenance Technician', '2025-10-04');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (265, 'Willy', 'Fautly', 'Facility Coordinator', '2025-07-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (266, 'Leigha', 'Boylund', 'Cleaner', '2025-03-30');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (267, 'Shea', 'Caseley', 'Equipment Specialist', '2025-12-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (268, 'Ara', 'Grace', 'Operations Manager', '2025-11-23');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (269, 'Mildred', 'Glendinning', 'Cleaner', '2025-08-02');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (270, 'Hildagard', 'McDonald', 'Electrician', '2025-08-13');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (271, 'Maryann', 'Kavanagh', 'Equipment Specialist', '2026-03-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (272, 'Doro', 'Carnock', 'Operations Manager', '2025-12-28');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (273, 'Bunny', 'Lowrie', 'Operations Manager', '2025-08-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (274, 'Agustin', 'McAsgill', 'Equipment Specialist', '2025-10-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (275, 'Rivalee', 'Carryer', 'Facility Coordinator', '2025-03-26');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (276, 'Isiahi', 'Courtier', 'Facility Coordinator', '2025-10-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (277, 'Nance', 'Follan', 'Equipment Specialist', '2025-11-10');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (278, 'Aloysius', 'Hincham', 'Maintenance Technician', '2025-11-05');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (279, 'Esme', 'Chillingsworth', 'Operations Manager', '2025-06-05');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (280, 'Edmund', 'Durrans', 'Operations Manager', '2025-10-07');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (281, 'Addison', 'Foucar', 'Cleaner', '2025-11-12');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (282, 'Lowell', 'Bedinn', 'Equipment Specialist', '2025-05-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (283, 'Ellie', 'Iredale', 'Electrician', '2025-07-21');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (284, 'Perle', 'Larcher', 'Maintenance Technician', '2025-12-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (285, 'Shep', 'Keen', 'Electrician', '2026-01-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (286, 'Ronda', 'Pound', 'Maintenance Technician', '2025-10-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (287, 'Chrysa', 'Valder', 'Maintenance Technician', '2025-06-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (288, 'Kathryn', 'Tessington', 'Electrician', '2025-07-02');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (289, 'Patrica', 'Hanning', 'Operations Manager', '2025-10-17');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (290, 'Asher', 'Besset', 'Facility Coordinator', '2025-05-07');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (291, 'Sherie', 'Codrington', 'Maintenance Technician', '2025-10-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (292, 'Kathryn', 'Stopps', 'Equipment Specialist', '2025-07-31');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (293, 'Livia', 'Fulger', 'Equipment Specialist', '2025-06-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (294, 'Kerrie', 'Fedorski', 'Facility Coordinator', '2025-12-21');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (295, 'Dennis', 'Lingwood', 'Cleaner', '2026-02-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (296, 'Karna', 'Philippson', 'Cleaner', '2026-02-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (297, 'Ezechiel', 'Beddow', 'Electrician', '2026-01-16');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (298, 'Ebonee', 'Kynastone', 'Operations Manager', '2025-09-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (299, 'Nickie', 'Skeete', 'Electrician', '2025-09-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (300, 'Dannel', 'Halfhide', 'Electrician', '2025-05-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (301, 'Shirlene', 'Chapellow', 'Facility Coordinator', '2025-08-15');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (302, 'Oliviero', 'Hardey', 'Maintenance Technician', '2025-12-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (303, 'Hallie', 'Abley', 'Cleaner', '2025-10-31');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (304, 'Lulita', 'Tommasetti', 'Operations Manager', '2025-09-23');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (305, 'Decca', 'Veschambre', 'Operations Manager', '2025-05-13');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (306, 'Kristin', 'Dufaire', 'Facility Coordinator', '2025-09-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (307, 'Gerty', 'Bonas', 'Maintenance Technician', '2025-10-17');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (308, 'Olia', 'Shevlan', 'Equipment Specialist', '2025-11-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (309, 'Inigo', 'Garthland', 'Electrician', '2026-03-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (310, 'Tamarah', 'Carlick', 'Operations Manager', '2025-09-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (311, 'Dotti', 'Samudio', 'Maintenance Technician', '2026-02-22');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (312, 'Gabriella', 'Barrable', 'Electrician', '2025-12-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (313, 'Xenos', 'Macenzy', 'Facility Coordinator', '2025-12-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (314, 'Lynnell', 'Godlonton', 'Facility Coordinator', '2025-07-21');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (315, 'Jobey', 'Heritege', 'Facility Coordinator', '2026-01-10');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (316, 'Biddie', 'Beves', 'Equipment Specialist', '2025-04-10');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (317, 'Hy', 'Messum', 'Cleaner', '2026-03-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (318, 'Gypsy', 'Haining', 'Electrician', '2026-02-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (319, 'Emmanuel', 'Kestell', 'Electrician', '2025-05-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (320, 'Karry', 'Edel', 'Operations Manager', '2025-06-09');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (321, 'Sheppard', 'Guerreau', 'Cleaner', '2025-10-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (322, 'Abdel', 'Michael', 'Facility Coordinator', '2025-07-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (323, 'Nollie', 'Panketh', 'Facility Coordinator', '2025-06-02');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (324, 'Brook', 'Gould', 'Facility Coordinator', '2025-06-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (325, 'Adelheid', 'Ormiston', 'Electrician', '2025-07-17');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (326, 'Carlee', 'Giannazzo', 'Facility Coordinator', '2025-10-18');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (327, 'Lorna', 'Doale', 'Electrician', '2025-12-17');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (328, 'Rosabelle', 'Curado', 'Maintenance Technician', '2025-12-28');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (329, 'Adelice', 'Charlson', 'Facility Coordinator', '2025-11-28');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (330, 'Joleen', 'Corhard', 'Facility Coordinator', '2025-07-12');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (331, 'Arty', 'Warren', 'Electrician', '2025-08-09');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (332, 'Jordana', 'Titcom', 'Facility Coordinator', '2026-03-07');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (333, 'Tally', 'Kilrow', 'Electrician', '2025-09-17');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (334, 'Eula', 'Stileman', 'Equipment Specialist', '2026-02-20');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (335, 'Loralie', 'Lange', 'Maintenance Technician', '2025-08-05');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (336, 'Hayley', 'Strettle', 'Operations Manager', '2026-01-08');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (337, 'Felicio', 'Witcombe', 'Facility Coordinator', '2025-12-02');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (338, 'Melanie', 'Philpott', 'Electrician', '2025-11-28');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (339, 'Doug', 'Mattack', 'Facility Coordinator', '2025-11-20');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (340, 'Annabell', 'Obee', 'Equipment Specialist', '2025-04-23');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (341, 'Ramsey', 'Banasiak', 'Operations Manager', '2025-04-05');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (342, 'Giana', 'Pilmore', 'Electrician', '2026-01-09');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (343, 'Giustino', 'Prandi', 'Operations Manager', '2025-11-02');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (344, 'Ardine', 'Allum', 'Maintenance Technician', '2026-01-17');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (345, 'Sadella', 'Teodorski', 'Cleaner', '2025-11-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (346, 'Pasquale', 'Rough', 'Cleaner', '2025-11-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (347, 'Vanya', 'Buglar', 'Electrician', '2026-01-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (348, 'Flori', 'Belham', 'Operations Manager', '2026-02-27');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (349, 'Tore', 'Verzey', 'Cleaner', '2025-10-08');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (350, 'Marco', 'Sambells', 'Electrician', '2025-07-22');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (351, 'Waneta', 'Romme', 'Equipment Specialist', '2026-02-28');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (352, 'Caesar', 'Pinckney', 'Electrician', '2026-03-16');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (353, 'Deana', 'Keyho', 'Equipment Specialist', '2025-07-23');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (354, 'Shannon', 'Lemanu', 'Electrician', '2025-06-23');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (355, 'Ferdinand', 'Filipychev', 'Electrician', '2025-10-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (356, 'Alvinia', 'Knowles', 'Operations Manager', '2025-05-26');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (357, 'Ginnie', 'Anderbrugge', 'Equipment Specialist', '2025-07-12');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (358, 'Jere', 'Kimber', 'Facility Coordinator', '2025-10-02');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (359, 'Murray', 'Cammis', 'Electrician', '2025-11-26');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (360, 'Katya', 'Spavon', 'Maintenance Technician', '2025-12-18');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (361, 'Dud', 'MacGiffin', 'Operations Manager', '2025-06-21');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (362, 'Base', 'Mathelin', 'Cleaner', '2025-09-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (363, 'Myrwyn', 'Treske', 'Maintenance Technician', '2026-02-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (364, 'Mycah', 'Nolton', 'Operations Manager', '2025-07-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (365, 'Traci', 'Ambrogiotti', 'Facility Coordinator', '2025-09-20');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (366, 'Ainslee', 'Persian', 'Operations Manager', '2025-10-27');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (367, 'Merrie', 'Dallaway', 'Electrician', '2025-07-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (368, 'Ailee', 'Belamy', 'Cleaner', '2026-01-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (369, 'Wallace', 'Flucks', 'Cleaner', '2026-03-23');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (370, 'Dani', 'Belitz', 'Facility Coordinator', '2025-04-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (371, 'Breanne', 'Sketchley', 'Operations Manager', '2025-10-31');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (372, 'Marie-ann', 'Hatt', 'Maintenance Technician', '2026-01-22');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (373, 'Beatrisa', 'Jaye', 'Equipment Specialist', '2025-11-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (374, 'Adriaens', 'Gosland', 'Cleaner', '2025-04-18');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (375, 'Melony', 'Tantum', 'Equipment Specialist', '2025-11-27');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (376, 'Valene', 'Clues', 'Facility Coordinator', '2025-04-22');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (377, 'Harwilll', 'Pickance', 'Cleaner', '2025-06-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (378, 'Gerhard', 'Westhead', 'Electrician', '2025-06-04');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (379, 'Cirilo', 'Weeks', 'Equipment Specialist', '2025-04-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (380, 'Ansel', 'Kyd', 'Equipment Specialist', '2025-11-30');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (381, 'Shepherd', 'Timbridge', 'Cleaner', '2025-05-20');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (382, 'Lefty', 'Hughlin', 'Electrician', '2025-12-07');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (383, 'Phoebe', 'Matuska', 'Facility Coordinator', '2025-05-30');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (384, 'Ethe', 'Blaycock', 'Electrician', '2025-07-09');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (385, 'Shalne', 'Kollas', 'Cleaner', '2026-01-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (386, 'Ebony', 'Helsby', 'Operations Manager', '2025-08-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (387, 'Erskine', 'Cosgry', 'Operations Manager', '2025-10-17');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (388, 'Byron', 'Bodycomb', 'Equipment Specialist', '2025-10-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (389, 'Zitella', 'Borland', 'Facility Coordinator', '2025-09-15');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (390, 'Tudor', 'Varker', 'Maintenance Technician', '2025-07-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (391, 'Pincas', 'Niemetz', 'Facility Coordinator', '2025-06-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (392, 'Myra', 'Newvill', 'Maintenance Technician', '2026-01-27');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (393, 'Jocelyn', 'Bitchener', 'Electrician', '2025-12-18');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (394, 'Urbano', 'McDougald', 'Maintenance Technician', '2025-05-16');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (395, 'Bathsheba', 'Fitzharris', 'Electrician', '2025-08-08');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (396, 'Fields', 'Corpe', 'Cleaner', '2025-10-30');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (397, 'Humberto', 'Bennetts', 'Maintenance Technician', '2025-11-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (398, 'Kendal', 'Ronaghan', 'Facility Coordinator', '2025-10-18');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (399, 'Kriste', 'Skaife', 'Electrician', '2025-12-10');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (400, 'Atlanta', 'Perrigo', 'Facility Coordinator', '2025-10-04');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (401, 'Toddy', 'Pinckney', 'Electrician', '2025-03-27');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (402, 'Dare', 'Barwise', 'Facility Coordinator', '2026-01-16');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (403, 'Gay', 'Maskell', 'Cleaner', '2026-01-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (404, 'Zia', 'Strooband', 'Facility Coordinator', '2026-02-10');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (405, 'Vinny', 'Wiffield', 'Equipment Specialist', '2025-06-14');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (406, 'Thedrick', 'Corzon', 'Cleaner', '2025-11-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (407, 'Kiri', 'Levis', 'Operations Manager', '2025-09-23');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (408, 'Sherman', 'Keasey', 'Cleaner', '2025-05-12');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (409, 'El', 'Pashen', 'Operations Manager', '2025-07-22');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (410, 'Dudley', 'Blowin', 'Facility Coordinator', '2025-12-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (411, 'Neila', 'Breeds', 'Cleaner', '2025-08-31');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (412, 'Olenka', 'Waddington', 'Maintenance Technician', '2026-02-14');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (413, 'Tirrell', 'Christophle', 'Facility Coordinator', '2025-11-23');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (414, 'Jordanna', 'Eayres', 'Equipment Specialist', '2025-10-14');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (415, 'Carolann', 'Ratnage', 'Facility Coordinator', '2025-12-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (416, 'Ermin', 'Comar', 'Maintenance Technician', '2025-07-30');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (417, 'Joyan', 'Harteley', 'Maintenance Technician', '2025-04-05');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (418, 'Jacobo', 'Coulston', 'Maintenance Technician', '2025-08-21');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (419, 'Myrna', 'Fothergill', 'Equipment Specialist', '2025-05-07');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (420, 'Nissie', 'Jovey', 'Operations Manager', '2026-02-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (421, 'Allix', 'Beardwell', 'Equipment Specialist', '2025-05-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (422, 'Georgianne', 'Purcell', 'Electrician', '2025-06-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (423, 'Gilli', 'Duffield', 'Facility Coordinator', '2025-07-05');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (424, 'Berni', 'Lineham', 'Maintenance Technician', '2025-07-20');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (425, 'Mohammed', 'Brierly', 'Facility Coordinator', '2026-01-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (426, 'Asa', 'Wixey', 'Electrician', '2025-04-22');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (427, 'Mark', 'Schistl', 'Cleaner', '2025-04-08');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (428, 'Lorne', 'Kaubisch', 'Cleaner', '2025-08-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (429, 'Cinda', 'Bythell', 'Operations Manager', '2025-09-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (430, 'Erik', 'Guilfoyle', 'Facility Coordinator', '2025-03-30');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (431, 'Lillian', 'Clemow', 'Facility Coordinator', '2025-10-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (432, 'Hadria', 'Slyde', 'Facility Coordinator', '2025-06-04');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (433, 'Randi', 'Walne', 'Facility Coordinator', '2025-12-21');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (434, 'Vachel', 'Torrejon', 'Equipment Specialist', '2025-05-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (435, 'Marcellina', 'Ogles', 'Cleaner', '2025-08-31');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (436, 'Chaddy', 'Proud', 'Equipment Specialist', '2026-01-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (437, 'Rick', 'Skermer', 'Maintenance Technician', '2026-02-13');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (438, 'Ulrich', 'Davana', 'Equipment Specialist', '2025-11-09');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (439, 'Steffen', 'Pohling', 'Facility Coordinator', '2026-03-07');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (440, 'Marley', 'Ballam', 'Maintenance Technician', '2026-01-11');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (441, 'Dede', 'Poff', 'Electrician', '2025-10-21');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (442, 'Kathryne', 'Stickney', 'Facility Coordinator', '2025-08-08');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (443, 'Netty', 'Breddy', 'Equipment Specialist', '2026-02-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (444, 'Olive', 'Abercromby', 'Operations Manager', '2025-09-22');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (445, 'Oneida', 'Crayton', 'Maintenance Technician', '2025-12-28');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (446, 'Vlad', 'Whibley', 'Electrician', '2025-06-15');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (447, 'Krispin', 'Stewart', 'Maintenance Technician', '2025-12-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (448, 'Cicely', 'Stitle', 'Equipment Specialist', '2025-10-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (449, 'Ellswerth', 'Wooder', 'Equipment Specialist', '2025-06-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (450, 'Estele', 'McConnal', 'Facility Coordinator', '2025-07-30');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (451, 'Ford', 'Frotton', 'Operations Manager', '2025-12-05');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (452, 'Sonnnie', 'Milner', 'Electrician', '2025-11-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (453, 'Teressa', 'Taffrey', 'Equipment Specialist', '2025-10-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (454, 'Wenona', 'Alston', 'Operations Manager', '2026-02-18');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (455, 'Scot', 'O''Feeney', 'Facility Coordinator', '2025-10-04');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (456, 'Colline', 'Muspratt', 'Equipment Specialist', '2026-03-14');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (457, 'Walt', 'Stiggers', 'Operations Manager', '2025-04-30');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (458, 'Nikola', 'Blum', 'Electrician', '2025-09-25');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (459, 'Jessi', 'Wearing', 'Equipment Specialist', '2025-06-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (460, 'Alia', 'Seatter', 'Operations Manager', '2025-12-15');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (461, 'Demeter', 'Breffitt', 'Equipment Specialist', '2025-09-28');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (462, 'Asia', 'Vedikhov', 'Operations Manager', '2026-03-18');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (463, 'Celka', 'Pendre', 'Operations Manager', '2025-06-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (464, 'Mordy', 'Davidowsky', 'Equipment Specialist', '2026-03-16');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (465, 'Jacqueline', 'Lappine', 'Facility Coordinator', '2025-09-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (466, 'Arlin', 'Evenden', 'Equipment Specialist', '2025-12-14');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (467, 'Nicholas', 'Ternent', 'Facility Coordinator', '2026-03-07');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (468, 'Hogan', 'Sigsworth', 'Electrician', '2025-05-31');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (469, 'Mollie', 'Oger', 'Electrician', '2025-08-02');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (470, 'Guillema', 'Carsey', 'Operations Manager', '2025-06-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (471, 'Marisa', 'Charrington', 'Cleaner', '2025-09-30');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (472, 'Charyl', 'Baudains', 'Operations Manager', '2025-09-27');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (473, 'Faulkner', 'Chatin', 'Cleaner', '2026-02-08');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (474, 'Vaughn', 'Lotze', 'Equipment Specialist', '2026-02-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (475, 'Glenda', 'Luppitt', 'Electrician', '2025-10-29');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (476, 'Ashlan', 'Paice', 'Equipment Specialist', '2025-05-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (477, 'Ricca', 'McReedy', 'Maintenance Technician', '2026-02-23');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (478, 'Abel', 'Holdron', 'Electrician', '2025-12-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (479, 'Todd', 'Mulliss', 'Equipment Specialist', '2026-02-14');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (480, 'Feodor', 'Valentine', 'Operations Manager', '2025-10-07');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (481, 'Jarvis', 'Pigeram', 'Electrician', '2025-03-30');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (482, 'Rani', 'Cathee', 'Cleaner', '2025-09-18');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (483, 'Lorie', 'Bentham', 'Cleaner', '2026-03-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (484, 'Karita', 'Stidworthy', 'Facility Coordinator', '2025-08-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (485, 'Norbie', 'Duerdin', 'Facility Coordinator', '2025-04-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (486, 'Lemmie', 'Sawood', 'Operations Manager', '2026-01-31');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (487, 'Godiva', 'Murkitt', 'Cleaner', '2025-08-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (488, 'Mal', 'Bowden', 'Electrician', '2025-11-04');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (489, 'Zia', 'Crimes', 'Maintenance Technician', '2025-11-07');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (490, 'Mickey', 'Bromwich', 'Maintenance Technician', '2025-08-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (491, 'Siward', 'Kennington', 'Operations Manager', '2025-06-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (492, 'Brittne', 'Lythgoe', 'Maintenance Technician', '2026-01-18');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (493, 'Wait', 'O''Neil', 'Electrician', '2025-04-28');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (494, 'Cyndi', 'Chesterfield', 'Operations Manager', '2025-12-17');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (495, 'Clary', 'Brickstock', 'Cleaner', '2025-05-06');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (496, 'Putnem', 'Beardsell', 'Operations Manager', '2025-09-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (497, 'Ramona', 'Balharrie', 'Operations Manager', '2026-01-18');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (498, 'Hakim', 'Clutram', 'Cleaner', '2026-03-20');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (499, 'Stuart', 'Blinco', 'Operations Manager', '2025-07-07');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (500, 'Inger', 'Ivakhnov', 'Equipment Specialist', '2025-09-20');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (501, 'Mia', 'Clayson', 'Cleaner', '2026-02-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (502, 'Gwendolin', 'Beasant', 'Operations Manager', '2025-08-24');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (503, 'Caspar', 'Kures', 'Operations Manager', '2025-06-19');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (504, 'Milena', 'Brownsmith', 'Facility Coordinator', '2025-06-13');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (505, 'Stanleigh', 'Bonus', 'Facility Coordinator', '2026-01-16');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (506, 'Allissa', 'Petto', 'Cleaner', '2026-01-01');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (507, 'Audre', 'Cowherd', 'Electrician', '2025-07-03');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (508, 'Mabel', 'McQuorkel', 'Equipment Specialist', '2025-10-12');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (509, 'Dominick', 'Cunrado', 'Equipment Specialist', '2025-07-16');
insert into EMPLOYEE (Employee_ID, First_Name, Last_Name, Job_Title, Hire_Date) values (510, 'Malissa', 'Pionter', 'Cleaner', '2026-01-07');
