insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-1', 'Free Weights Area', 23, 260.94);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-2', 'Main Gym Floor', 77, 294.74);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-3', 'CrossFit Box', 87, 217.02);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-4', 'Martial Arts Dojo', 37, 154.22);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-5', 'Cardio Zone', 29, 72.52);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-6', 'Functional Training Zone', 10, 78.49);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-7', 'Outdoor Training Area', 30, 153.59);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-8', 'Pilates Studio', 42, 190.89);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-9', 'Swimming Pool', 14, 91.17);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-10', 'Martial Arts Dojo', 66, 90.9);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-11', 'Functional Training Zone', 23, 292.3);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-12', 'CrossFit Box', 94, 170.24);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-13', 'Spinning Room', 17, 76.94);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-14', 'Martial Arts Dojo', 35, 90.06);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-15', 'Spinning Room', 37, 84.12);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-16', 'Stretching Area', 60, 283.08);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-17', 'Cardio Zone', 79, 77.82);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-18', 'Pilates Studio', 13, 199.09);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-19', 'Pilates Studio', 29, 217.96);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-20', 'Martial Arts Dojo', 25, 137.32);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-21', 'Spinning Room', 73, 107.61);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-22', 'Swimming Pool', 97, 100.63);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-23', 'Spinning Room', 45, 214.06);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-24', 'Free Weights Area', 74, 188.92);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-25', 'Swimming Pool', 74, 160.4);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-26', 'CrossFit Box', 61, 174.73);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-27', 'CrossFit Box', 35, 249.44);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-28', 'Martial Arts Dojo', 65, 141.76);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-29', 'Cardio Zone', 85, 196.71);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-30', 'VIP Lounge', 13, 220.51);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-31', 'Outdoor Training Area', 12, 291.05);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-32', 'Outdoor Training Area', 22, 247.45);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-33', 'Cardio Zone', 46, 158.27);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-34', 'Free Weights Area', 87, 261.94);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-35', 'Outdoor Training Area', 69, 224.73);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-36', 'Yoga Studio', 19, 84.62);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-37', 'Cardio Zone', 16, 68.68);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-38', 'CrossFit Box', 34, 205.68);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-39', 'Swimming Pool', 58, 245.18);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-40', 'VIP Lounge', 44, 73.08);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-41', 'Swimming Pool', 24, 268.93);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-42', 'Swimming Pool', 76, 119.1);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-43', 'Martial Arts Dojo', 15, 267.88);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-44', 'VIP Lounge', 69, 287.5);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-45', 'Main Gym Floor', 49, 129.69);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-46', 'Outdoor Training Area', 22, 51.81);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-47', 'Yoga Studio', 26, 137.55);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-48', 'Swimming Pool', 65, 202.77);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-49', 'Functional Training Zone', 11, 262.35);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-50', 'Spinning Room', 98, 77.6);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-51', 'Yoga Studio', 93, 62.18);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-52', 'Yoga Studio', 53, 220.84);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-53', 'CrossFit Box', 93, 154.39);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-54', 'Martial Arts Dojo', 83, 291.36);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-55', 'Free Weights Area', 16, 254.69);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-56', 'Functional Training Zone', 96, 210.19);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-57', 'Pilates Studio', 77, 103.64);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-58', 'Free Weights Area', 24, 230.56);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-59', 'Martial Arts Dojo', 13, 254.41);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-60', 'Martial Arts Dojo', 26, 166.34);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-61', 'Spinning Room', 12, 123.31);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-62', 'Stretching Area', 52, 284.7);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-63', 'Yoga Studio', 28, 195.88);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-64', 'Outdoor Training Area', 78, 169.44);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-65', 'Spinning Room', 54, 249.4);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-66', 'CrossFit Box', 70, 256.47);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-67', 'Free Weights Area', 100, 119.57);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-68', 'Yoga Studio', 68, 272.1);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-69', 'Pilates Studio', 87, 158.6);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-70', 'VIP Lounge', 58, 292.29);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-71', 'Yoga Studio', 50, 244.97);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-72', 'Yoga Studio', 35, 226.97);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-73', 'Cardio Zone', 98, 215.34);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-74', 'Yoga Studio', 94, 150.32);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-75', 'CrossFit Box', 29, 68.75);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-76', 'Free Weights Area', 29, 64.26);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-77', 'Outdoor Training Area', 70, 206.0);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-78', 'Outdoor Training Area', 31, 247.82);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-79', 'Main Gym Floor', 90, 100.67);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-80', 'Spinning Room', 88, 187.25);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-81', 'Functional Training Zone', 34, 83.37);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-82', 'CrossFit Box', 14, 173.28);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-83', 'Spinning Room', 10, 86.63);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-84', 'Outdoor Training Area', 14, 285.64);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-85', 'Martial Arts Dojo', 22, 273.22);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-86', 'Free Weights Area', 45, 94.72);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-87', 'Stretching Area', 100, 265.45);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-88', 'Stretching Area', 79, 115.89);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-89', 'CrossFit Box', 40, 140.11);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-90', 'Pilates Studio', 54, 92.83);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-91', 'Yoga Studio', 69, 184.82);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-92', 'Functional Training Zone', 36, 76.57);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-93', 'CrossFit Box', 95, 286.97);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-94', 'Swimming Pool', 83, 118.64);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-95', 'Spinning Room', 20, 128.39);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-96', 'Free Weights Area', 98, 137.64);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-97', 'Stretching Area', 43, 217.47);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-98', 'Main Gym Floor', 25, 182.36);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-99', 'VIP Lounge', 25, 164.74);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-100', 'Yoga Studio', 17, 148.51);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-101', 'Stretching Area', 34, 201.57);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-102', 'Free Weights Area', 18, 205.18);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-103', 'Main Gym Floor', 88, 247.0);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-104', 'Pilates Studio', 57, 167.12);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-105', 'Pilates Studio', 11, 297.57);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-106', 'Martial Arts Dojo', 57, 125.91);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-107', 'Martial Arts Dojo', 55, 157.97);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-108', 'Martial Arts Dojo', 28, 259.6);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-109', 'Yoga Studio', 15, 134.3);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-110', 'Yoga Studio', 72, 173.44);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-111', 'Martial Arts Dojo', 18, 258.06);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-112', 'Swimming Pool', 92, 90.64);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-113', 'Pilates Studio', 65, 137.63);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-114', 'Free Weights Area', 16, 256.89);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-115', 'Free Weights Area', 66, 97.99);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-116', 'VIP Lounge', 80, 257.3);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-117', 'Spinning Room', 54, 257.74);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-118', 'Cardio Zone', 88, 218.91);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-119', 'Swimming Pool', 78, 180.62);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-120', 'CrossFit Box', 11, 180.88);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-121', 'Spinning Room', 89, 146.66);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-122', 'Outdoor Training Area', 47, 209.8);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-123', 'Martial Arts Dojo', 62, 144.63);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-124', 'Outdoor Training Area', 33, 189.67);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-125', 'VIP Lounge', 23, 77.85);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-126', 'Free Weights Area', 50, 236.04);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-127', 'Swimming Pool', 22, 182.86);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-128', 'Functional Training Zone', 46, 70.18);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-129', 'VIP Lounge', 92, 190.04);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-130', 'Stretching Area', 98, 147.67);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-131', 'VIP Lounge', 77, 58.09);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-132', 'Main Gym Floor', 49, 77.26);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-133', 'Cardio Zone', 88, 208.67);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-134', 'Swimming Pool', 90, 171.94);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-135', 'Main Gym Floor', 80, 153.52);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-136', 'Cardio Zone', 78, 179.04);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-137', 'Yoga Studio', 42, 196.29);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-138', 'CrossFit Box', 35, 246.04);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-139', 'Martial Arts Dojo', 75, 74.93);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-140', 'VIP Lounge', 87, 124.82);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-141', 'CrossFit Box', 49, 243.67);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-142', 'Spinning Room', 45, 295.72);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-143', 'Outdoor Training Area', 88, 247.29);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-144', 'Free Weights Area', 96, 88.77);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-145', 'CrossFit Box', 42, 262.39);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-146', 'Main Gym Floor', 26, 76.56);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-147', 'Cardio Zone', 48, 128.57);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-148', 'Free Weights Area', 68, 124.39);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-149', 'Yoga Studio', 38, 190.4);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-150', 'Pilates Studio', 44, 68.34);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-151', 'Yoga Studio', 30, 165.85);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-152', 'Yoga Studio', 59, 178.98);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-153', 'Swimming Pool', 45, 59.65);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-154', 'Swimming Pool', 73, 183.56);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-155', 'Stretching Area', 44, 229.21);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-156', 'Free Weights Area', 91, 217.31);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-157', 'VIP Lounge', 31, 178.62);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-158', 'VIP Lounge', 28, 139.26);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-159', 'Outdoor Training Area', 62, 264.75);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-160', 'Functional Training Zone', 81, 121.02);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-161', 'VIP Lounge', 83, 153.94);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-162', 'Functional Training Zone', 40, 271.79);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-163', 'Martial Arts Dojo', 41, 139.02);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-164', 'Cardio Zone', 78, 159.35);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-165', 'VIP Lounge', 83, 80.87);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-166', 'Pilates Studio', 92, 81.92);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-167', 'Yoga Studio', 30, 110.17);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-168', 'CrossFit Box', 49, 292.11);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-169', 'Cardio Zone', 21, 224.31);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-170', 'Yoga Studio', 71, 235.16);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-171', 'Main Gym Floor', 40, 107.33);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-172', 'CrossFit Box', 30, 62.42);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-173', 'Martial Arts Dojo', 46, 142.4);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-174', 'Pilates Studio', 84, 177.81);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-175', 'Main Gym Floor', 62, 52.14);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-176', 'Outdoor Training Area', 73, 169.89);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-177', 'Swimming Pool', 89, 67.44);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-178', 'Swimming Pool', 54, 161.33);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-179', 'Functional Training Zone', 29, 138.27);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-180', 'Main Gym Floor', 69, 58.47);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-181', 'Martial Arts Dojo', 23, 163.84);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-182', 'Main Gym Floor', 33, 273.8);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-183', 'Main Gym Floor', 44, 232.77);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-184', 'Free Weights Area', 10, 126.5);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-185', 'Spinning Room', 15, 258.56);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-186', 'Outdoor Training Area', 57, 200.96);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-187', 'Spinning Room', 11, 68.08);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-188', 'Stretching Area', 51, 148.04);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-189', 'CrossFit Box', 88, 241.85);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-190', 'Functional Training Zone', 72, 59.84);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-191', 'Free Weights Area', 44, 178.6);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-192', 'VIP Lounge', 12, 282.17);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-193', 'Pilates Studio', 43, 127.85);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-194', 'Main Gym Floor', 35, 148.48);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-195', 'Functional Training Zone', 96, 74.41);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-196', 'Functional Training Zone', 57, 148.4);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-197', 'Swimming Pool', 87, 201.29);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-198', 'Main Gym Floor', 76, 146.47);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-199', 'CrossFit Box', 77, 240.75);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-200', 'Functional Training Zone', 87, 271.86);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-201', 'Outdoor Training Area', 53, 268.64);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-202', 'Yoga Studio', 95, 122.55);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-203', 'Free Weights Area', 38, 289.15);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-204', 'Free Weights Area', 78, 250.43);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-205', 'Stretching Area', 59, 198.63);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-206', 'Cardio Zone', 93, 278.96);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-207', 'Main Gym Floor', 59, 198.43);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-208', 'CrossFit Box', 21, 95.48);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-209', 'Free Weights Area', 58, 69.71);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-210', 'Stretching Area', 11, 64.18);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-211', 'Free Weights Area', 71, 210.54);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-212', 'Functional Training Zone', 75, 287.5);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-213', 'Cardio Zone', 83, 58.53);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-214', 'VIP Lounge', 16, 163.3);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-215', 'Outdoor Training Area', 39, 182.0);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-216', 'Martial Arts Dojo', 86, 62.34);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-217', 'Martial Arts Dojo', 65, 242.93);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-218', 'Outdoor Training Area', 18, 234.85);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-219', 'VIP Lounge', 100, 280.38);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-220', 'Main Gym Floor', 44, 298.93);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-221', 'Main Gym Floor', 20, 50.26);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-222', 'Yoga Studio', 91, 169.51);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-223', 'Martial Arts Dojo', 57, 198.86);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-224', 'Outdoor Training Area', 82, 296.21);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-225', 'Yoga Studio', 15, 242.66);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-226', 'CrossFit Box', 44, 202.75);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-227', 'Swimming Pool', 92, 224.84);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-228', 'Pilates Studio', 64, 290.08);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-229', 'Cardio Zone', 22, 118.1);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-230', 'Free Weights Area', 59, 128.88);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-231', 'Free Weights Area', 85, 61.56);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-232', 'Swimming Pool', 89, 81.96);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-233', 'Yoga Studio', 95, 54.66);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-234', 'Swimming Pool', 98, 141.13);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-235', 'Yoga Studio', 94, 157.48);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-236', 'Cardio Zone', 80, 61.05);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-237', 'Main Gym Floor', 27, 275.67);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-238', 'Swimming Pool', 43, 207.56);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-239', 'Main Gym Floor', 55, 68.61);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-240', 'Functional Training Zone', 98, 213.22);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-241', 'Pilates Studio', 71, 157.8);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-242', 'Functional Training Zone', 95, 159.94);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-243', 'Spinning Room', 57, 170.95);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-244', 'Cardio Zone', 56, 55.74);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-245', 'Yoga Studio', 47, 104.0);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-246', 'Martial Arts Dojo', 36, 268.22);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-247', 'VIP Lounge', 92, 295.56);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-248', 'Pilates Studio', 32, 209.68);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-249', 'Swimming Pool', 84, 268.63);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-250', 'Main Gym Floor', 96, 272.89);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-251', 'VIP Lounge', 51, 238.16);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-252', 'Martial Arts Dojo', 33, 294.5);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-253', 'Yoga Studio', 80, 101.15);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-254', 'Main Gym Floor', 66, 115.11);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-255', 'Yoga Studio', 17, 243.9);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-256', 'Pilates Studio', 25, 94.51);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-257', 'Swimming Pool', 45, 227.75);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-258', 'CrossFit Box', 39, 76.18);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-259', 'Pilates Studio', 78, 156.17);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-260', 'Free Weights Area', 80, 223.63);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-261', 'CrossFit Box', 16, 299.85);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-262', 'Swimming Pool', 13, 151.73);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-263', 'Main Gym Floor', 22, 63.51);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-264', 'CrossFit Box', 30, 135.92);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-265', 'Swimming Pool', 50, 241.73);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-266', 'VIP Lounge', 52, 273.76);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-267', 'VIP Lounge', 49, 263.17);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-268', 'Stretching Area', 19, 157.43);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-269', 'Free Weights Area', 11, 250.61);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-270', 'Outdoor Training Area', 30, 80.25);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-271', 'Pilates Studio', 52, 111.36);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-272', 'Outdoor Training Area', 79, 55.74);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-273', 'Cardio Zone', 57, 124.56);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-274', 'VIP Lounge', 20, 260.31);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-275', 'VIP Lounge', 41, 284.31);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-276', 'Martial Arts Dojo', 34, 118.18);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-277', 'Main Gym Floor', 55, 150.73);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-278', 'Free Weights Area', 82, 116.8);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-279', 'Yoga Studio', 81, 108.82);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-280', 'VIP Lounge', 65, 55.7);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-281', 'CrossFit Box', 44, 204.88);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-282', 'VIP Lounge', 63, 185.85);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-283', 'Stretching Area', 20, 242.83);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-284', 'Pilates Studio', 15, 182.11);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-285', 'Outdoor Training Area', 51, 69.29);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-286', 'Main Gym Floor', 34, 115.55);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-287', 'Pilates Studio', 97, 294.09);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-288', 'Stretching Area', 26, 95.96);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-289', 'VIP Lounge', 36, 114.6);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-290', 'Outdoor Training Area', 74, 116.33);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-291', 'Outdoor Training Area', 27, 168.14);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-292', 'Free Weights Area', 49, 296.7);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-293', 'Pilates Studio', 33, 133.42);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-294', 'Yoga Studio', 64, 239.35);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-295', 'Main Gym Floor', 12, 213.81);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-296', 'Spinning Room', 56, 146.47);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-297', 'Stretching Area', 36, 123.13);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-298', 'Stretching Area', 46, 297.56);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-299', 'Yoga Studio', 69, 97.69);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-300', 'Functional Training Zone', 40, 134.05);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-301', 'Main Gym Floor', 42, 55.48);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-302', 'VIP Lounge', 50, 179.47);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-303', 'Swimming Pool', 90, 259.59);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-304', 'Spinning Room', 11, 291.79);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-305', 'Martial Arts Dojo', 36, 90.38);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-306', 'Yoga Studio', 46, 131.7);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-307', 'Spinning Room', 20, 171.52);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-308', 'Spinning Room', 85, 284.54);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-309', 'Outdoor Training Area', 30, 165.87);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-310', 'Martial Arts Dojo', 19, 185.48);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-311', 'Outdoor Training Area', 15, 51.17);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-312', 'Martial Arts Dojo', 84, 224.48);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-313', 'Outdoor Training Area', 46, 257.47);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-314', 'Yoga Studio', 81, 81.76);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-315', 'Swimming Pool', 12, 192.04);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-316', 'CrossFit Box', 21, 213.42);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-317', 'Cardio Zone', 32, 269.56);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-318', 'Swimming Pool', 21, 72.21);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-319', 'CrossFit Box', 97, 153.8);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-320', 'Yoga Studio', 49, 225.06);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-321', 'Functional Training Zone', 84, 269.64);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-322', 'Cardio Zone', 60, 141.1);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-323', 'Cardio Zone', 42, 102.08);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-324', 'Spinning Room', 26, 128.03);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-325', 'Swimming Pool', 54, 267.9);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-326', 'Main Gym Floor', 22, 64.94);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-327', 'VIP Lounge', 46, 147.07);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-328', 'Cardio Zone', 78, 230.98);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-329', 'VIP Lounge', 40, 249.78);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-330', 'Spinning Room', 70, 144.36);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-331', 'Main Gym Floor', 39, 52.71);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-332', 'VIP Lounge', 93, 127.09);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-333', 'Stretching Area', 61, 241.22);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-334', 'Cardio Zone', 14, 87.6);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-335', 'Spinning Room', 85, 52.25);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-336', 'VIP Lounge', 64, 204.91);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-337', 'Cardio Zone', 21, 231.83);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-338', 'Cardio Zone', 98, 139.69);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-339', 'CrossFit Box', 15, 292.59);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-340', 'CrossFit Box', 15, 210.37);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-341', 'CrossFit Box', 85, 232.03);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-342', 'Cardio Zone', 36, 292.61);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-343', 'Spinning Room', 64, 125.22);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-344', 'Main Gym Floor', 18, 228.77);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-345', 'Spinning Room', 46, 101.03);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-346', 'Pilates Studio', 42, 168.88);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-347', 'CrossFit Box', 18, 198.27);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-348', 'Yoga Studio', 29, 193.98);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-349', 'CrossFit Box', 99, 200.32);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-350', 'Yoga Studio', 30, 123.94);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-351', 'VIP Lounge', 47, 97.29);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-352', 'Main Gym Floor', 60, 211.97);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-353', 'Stretching Area', 91, 165.49);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-354', 'Cardio Zone', 50, 293.69);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-355', 'VIP Lounge', 33, 115.94);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-356', 'Cardio Zone', 16, 259.3);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-357', 'Cardio Zone', 26, 172.83);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-358', 'Main Gym Floor', 30, 280.44);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-359', 'Functional Training Zone', 41, 197.38);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-360', 'Cardio Zone', 96, 240.28);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-361', 'Spinning Room', 73, 279.0);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-362', 'CrossFit Box', 32, 103.77);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-363', 'Free Weights Area', 75, 153.24);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-364', 'VIP Lounge', 73, 125.87);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-365', 'Functional Training Zone', 34, 109.85);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-366', 'Main Gym Floor', 52, 269.68);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-367', 'Outdoor Training Area', 90, 133.07);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-368', 'VIP Lounge', 29, 261.71);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-369', 'CrossFit Box', 24, 143.49);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-370', 'VIP Lounge', 53, 80.83);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-371', 'Outdoor Training Area', 29, 144.08);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-372', 'Outdoor Training Area', 50, 80.82);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-373', 'Free Weights Area', 67, 270.48);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-374', 'Stretching Area', 23, 272.39);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-375', 'Swimming Pool', 13, 143.15);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-376', 'Functional Training Zone', 94, 172.39);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-377', 'Martial Arts Dojo', 15, 258.5);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-378', 'Free Weights Area', 89, 297.17);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-379', 'Swimming Pool', 66, 246.91);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-380', 'Stretching Area', 39, 205.13);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-381', 'Yoga Studio', 95, 189.17);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-382', 'Martial Arts Dojo', 27, 247.28);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-383', 'Stretching Area', 17, 131.54);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-384', 'Cardio Zone', 77, 120.54);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-385', 'Cardio Zone', 38, 225.34);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-386', 'CrossFit Box', 75, 64.3);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-387', 'Swimming Pool', 37, 194.73);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-388', 'Martial Arts Dojo', 92, 211.96);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-389', 'Martial Arts Dojo', 24, 74.91);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-390', 'Martial Arts Dojo', 58, 154.4);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-391', 'Yoga Studio', 46, 70.13);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-392', 'Spinning Room', 76, 179.7);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-393', 'Stretching Area', 45, 156.54);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-394', 'Main Gym Floor', 12, 277.59);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-395', 'Functional Training Zone', 38, 88.6);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-396', 'Yoga Studio', 56, 78.32);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-397', 'VIP Lounge', 48, 65.58);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-398', 'Cardio Zone', 47, 63.84);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-399', 'Swimming Pool', 35, 140.45);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-400', 'Martial Arts Dojo', 92, 292.8);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-401', 'Cardio Zone', 25, 80.72);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-402', 'Swimming Pool', 68, 234.93);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-403', 'VIP Lounge', 21, 88.58);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-404', 'Free Weights Area', 26, 139.64);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-405', 'Swimming Pool', 90, 61.75);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-406', 'Pilates Studio', 41, 137.79);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-407', 'Free Weights Area', 71, 120.34);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-408', 'Swimming Pool', 12, 84.68);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-409', 'Cardio Zone', 96, 284.09);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-410', 'Functional Training Zone', 66, 206.32);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-411', 'Martial Arts Dojo', 91, 166.64);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-412', 'Main Gym Floor', 41, 203.51);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-413', 'Cardio Zone', 29, 114.62);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-414', 'Functional Training Zone', 30, 95.23);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-415', 'Free Weights Area', 96, 173.37);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-416', 'CrossFit Box', 68, 185.34);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-417', 'Swimming Pool', 35, 193.96);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-418', 'Spinning Room', 33, 152.36);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-419', 'Cardio Zone', 49, 256.75);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-420', 'Pilates Studio', 33, 290.56);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-421', 'Functional Training Zone', 63, 68.92);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-422', 'Spinning Room', 92, 195.85);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-423', 'Martial Arts Dojo', 24, 159.76);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-424', 'VIP Lounge', 46, 234.75);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-425', 'Free Weights Area', 18, 114.44);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-426', 'Martial Arts Dojo', 22, 210.7);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-427', 'Pilates Studio', 86, 194.76);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-428', 'CrossFit Box', 36, 267.37);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-429', 'Swimming Pool', 93, 94.72);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-430', 'Pilates Studio', 30, 77.98);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-431', 'Swimming Pool', 88, 199.63);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-432', 'Swimming Pool', 13, 202.89);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-433', 'Pilates Studio', 54, 158.32);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-434', 'Cardio Zone', 64, 53.87);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-435', 'Yoga Studio', 51, 233.88);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-436', 'Pilates Studio', 57, 194.29);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-437', 'Yoga Studio', 59, 125.98);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-438', 'Yoga Studio', 10, 274.02);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-439', 'Spinning Room', 74, 91.08);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-440', 'Pilates Studio', 30, 155.94);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-441', 'Stretching Area', 32, 184.2);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-442', 'Martial Arts Dojo', 71, 256.02);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-443', 'Main Gym Floor', 88, 130.15);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-444', 'Cardio Zone', 87, 270.73);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-445', 'Pilates Studio', 80, 178.16);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-446', 'Martial Arts Dojo', 80, 197.55);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-447', 'Main Gym Floor', 45, 158.11);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-448', 'Main Gym Floor', 50, 83.35);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-449', 'Pilates Studio', 20, 110.5);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-450', 'CrossFit Box', 96, 205.43);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-451', 'Functional Training Zone', 29, 122.05);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-452', 'CrossFit Box', 61, 287.97);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-453', 'Yoga Studio', 89, 293.74);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-454', 'VIP Lounge', 45, 182.78);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-455', 'Yoga Studio', 34, 220.59);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-456', 'Functional Training Zone', 14, 271.9);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-457', 'Martial Arts Dojo', 33, 175.55);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-458', 'Stretching Area', 32, 80.21);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-459', 'Main Gym Floor', 33, 186.36);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-460', 'Yoga Studio', 38, 111.05);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-461', 'Martial Arts Dojo', 74, 247.09);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-462', 'Yoga Studio', 36, 58.26);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-463', 'CrossFit Box', 51, 195.04);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-464', 'Functional Training Zone', 45, 78.32);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-465', 'VIP Lounge', 90, 105.58);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-466', 'Pilates Studio', 42, 91.09);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-467', 'Outdoor Training Area', 80, 83.52);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-468', 'Outdoor Training Area', 52, 235.88);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-469', 'Yoga Studio', 51, 118.36);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-470', 'CrossFit Box', 21, 202.21);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-471', 'Free Weights Area', 61, 256.22);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-472', 'Free Weights Area', 89, 188.04);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-473', 'Outdoor Training Area', 44, 69.94);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-474', 'Yoga Studio', 88, 84.07);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-475', 'Functional Training Zone', 15, 104.07);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-476', 'CrossFit Box', 69, 126.23);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-477', 'Free Weights Area', 68, 275.03);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-478', 'Free Weights Area', 56, 196.36);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-479', 'Stretching Area', 74, 232.01);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-480', 'VIP Lounge', 12, 293.06);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-481', 'VIP Lounge', 49, 218.81);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-482', 'Spinning Room', 44, 244.36);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-483', 'Pilates Studio', 55, 51.01);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-484', 'CrossFit Box', 36, 150.14);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-485', 'Swimming Pool', 81, 148.49);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-486', 'CrossFit Box', 70, 120.25);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-487', 'Spinning Room', 55, 154.28);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-488', 'Spinning Room', 76, 275.75);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-489', 'Martial Arts Dojo', 80, 91.52);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-490', 'Stretching Area', 20, 290.85);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-491', 'Stretching Area', 59, 292.07);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-492', 'Martial Arts Dojo', 100, 76.11);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-493', 'Functional Training Zone', 23, 124.99);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-494', 'Outdoor Training Area', 15, 66.27);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-495', 'Outdoor Training Area', 25, 263.18);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-496', 'Stretching Area', 50, 190.0);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-497', 'CrossFit Box', 63, 96.25);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-498', 'Cardio Zone', 55, 283.55);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-499', 'Yoga Studio', 100, 244.73);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-500', 'Martial Arts Dojo', 67, 217.15);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-501', 'Free Weights Area', 67, 141.72);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-502', 'Cardio Zone', 12, 204.49);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-503', 'Main Gym Floor', 34, 57.51);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-504', 'Stretching Area', 77, 193.0);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-505', 'Pilates Studio', 56, 224.48);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-506', 'Swimming Pool', 93, 55.19);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-507', 'VIP Lounge', 88, 208.54);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-508', 'Yoga Studio', 42, 278.7);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-509', 'Main Gym Floor', 90, 58.96);
insert into FACILITY_ZONE (Zone_Code, Zone_Name, Max_Capacity, Area_Sqm) values ('Z-510', 'Outdoor Training Area', 42, 229.82);
