insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-1', 'Hydraulic Piston', 36, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-2', 'Rubber Dumbbell End Cap', 26, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-3', 'Resistance Adjustment Knob', 50, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-4', 'Weight Stack Pin', 18, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-5', 'Pulley Wheel (Nylon)', 84, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-6', 'Display Console Overlay', 10, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-7', 'Handlebar Foam Grip', 51, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-8', 'Electronic Control Board', 80, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-9', 'Elliptical Foot Pedal', 92, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-10', 'Weight Stack Pin', 23, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-11', 'Roller Bearing', 59, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-12', 'Roller Bearing', 47, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-13', 'Pulley Wheel (Nylon)', 44, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-14', 'Resistance Adjustment Knob', 47, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-15', 'Resistance Adjustment Knob', 78, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-16', 'Heart Rate Sensor Grip', 1, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-17', 'Rubber Dumbbell End Cap', 2, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-18', 'Display Console Overlay', 64, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-19', 'Weight Stack Pin', 0, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-20', 'Weight Stack Pin', 38, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-21', 'Weight Stack Pin', 32, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-22', 'Roller Bearing', 32, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-23', 'Running Deck Lubricant', 42, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-24', 'Running Deck Lubricant', 88, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-25', 'Running Deck Lubricant', 94, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-26', 'Heart Rate Sensor Grip', 28, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-27', 'Stationary Bike Pedal Strap', 72, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-28', 'Weight Stack Pin', 19, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-29', 'Stationary Bike Pedal Strap', 26, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-30', 'Safety Stop Key', 45, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-31', 'Safety Stop Key', 82, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-32', 'Weight Stack Pin', 63, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-33', 'Running Deck Lubricant', 55, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-34', 'Rubber Dumbbell End Cap', 90, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-35', 'Strength Machine Cable (Steel)', 64, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-36', 'Display Console Overlay', 54, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-37', 'Rubber Dumbbell End Cap', 94, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-38', 'Battery for Cordless Machine', 69, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-39', 'Pulley Wheel (Nylon)', 1, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-40', 'Heart Rate Sensor Grip', 46, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-41', 'Stationary Bike Pedal Strap', 47, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-42', 'Pulley Wheel (Nylon)', 49, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-43', 'Safety Stop Key', 6, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-44', 'Running Deck Lubricant', 5, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-45', 'Display Console Overlay', 40, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-46', 'Electronic Control Board', 83, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-47', 'Electronic Control Board', 80, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-48', 'Pulley Wheel (Nylon)', 96, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-49', 'Safety Stop Key', 33, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-50', 'Stationary Bike Pedal Strap', 89, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-51', 'Heart Rate Sensor Grip', 77, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-52', 'Handlebar Foam Grip', 57, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-53', 'Safety Stop Key', 55, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-54', 'Heart Rate Sensor Grip', 95, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-55', 'Rubber Dumbbell End Cap', 6, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-56', 'Pulley Wheel (Nylon)', 14, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-57', 'Handlebar Foam Grip', 98, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-58', 'Stationary Bike Pedal Strap', 33, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-59', 'Hydraulic Piston', 15, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-60', 'Battery for Cordless Machine', 34, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-61', 'Elliptical Foot Pedal', 60, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-62', 'Roller Bearing', 82, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-63', 'Pulley Wheel (Nylon)', 1, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-64', 'Hydraulic Piston', 78, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-65', 'Hydraulic Piston', 56, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-66', 'Resistance Adjustment Knob', 22, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-67', 'Pulley Wheel (Nylon)', 90, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-68', 'Hydraulic Piston', 74, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-69', 'Weight Stack Pin', 88, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-70', 'Stationary Bike Pedal Strap', 82, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-71', 'Elliptical Foot Pedal', 93, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-72', 'Resistance Adjustment Knob', 99, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-73', 'Elliptical Foot Pedal', 58, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-74', 'Heart Rate Sensor Grip', 18, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-75', 'Safety Stop Key', 66, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-76', 'Treadmill Drive Belt', 99, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-77', 'Resistance Adjustment Knob', 59, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-78', 'Heart Rate Sensor Grip', 45, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-79', 'Stationary Bike Pedal Strap', 94, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-80', 'Treadmill Drive Belt', 45, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-81', 'Treadmill Drive Belt', 2, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-82', 'Safety Stop Key', 8, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-83', 'Handlebar Foam Grip', 72, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-84', 'Running Deck Lubricant', 8, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-85', 'Handlebar Foam Grip', 15, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-86', 'Treadmill Drive Belt', 83, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-87', 'Hydraulic Piston', 40, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-88', 'Resistance Adjustment Knob', 7, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-89', 'Running Deck Lubricant', 83, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-90', 'Pulley Wheel (Nylon)', 32, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-91', 'Battery for Cordless Machine', 19, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-92', 'Pulley Wheel (Nylon)', 27, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-93', 'Safety Stop Key', 3, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-94', 'Elliptical Foot Pedal', 5, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-95', 'Pulley Wheel (Nylon)', 9, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-96', 'Elliptical Foot Pedal', 59, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-97', 'Hydraulic Piston', 54, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-98', 'Running Deck Lubricant', 73, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-99', 'Resistance Adjustment Knob', 72, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-100', 'Pulley Wheel (Nylon)', 98, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-101', 'Pulley Wheel (Nylon)', 4, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-102', 'Strength Machine Cable (Steel)', 33, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-103', 'Running Deck Lubricant', 44, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-104', 'Strength Machine Cable (Steel)', 59, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-105', 'Electronic Control Board', 20, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-106', 'Rubber Dumbbell End Cap', 15, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-107', 'Hydraulic Piston', 46, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-108', 'Electronic Control Board', 8, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-109', 'Elliptical Foot Pedal', 62, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-110', 'Weight Stack Pin', 37, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-111', 'Strength Machine Cable (Steel)', 66, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-112', 'Roller Bearing', 55, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-113', 'Treadmill Drive Belt', 28, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-114', 'Rubber Dumbbell End Cap', 50, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-115', 'Display Console Overlay', 76, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-116', 'Safety Stop Key', 8, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-117', 'Safety Stop Key', 35, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-118', 'Elliptical Foot Pedal', 87, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-119', 'Stationary Bike Pedal Strap', 92, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-120', 'Pulley Wheel (Nylon)', 48, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-121', 'Battery for Cordless Machine', 28, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-122', 'Roller Bearing', 0, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-123', 'Roller Bearing', 83, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-124', 'Treadmill Drive Belt', 29, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-125', 'Strength Machine Cable (Steel)', 54, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-126', 'Heart Rate Sensor Grip', 74, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-127', 'Hydraulic Piston', 21, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-128', 'Bench Press Padding', 47, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-129', 'Heart Rate Sensor Grip', 95, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-130', 'Strength Machine Cable (Steel)', 30, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-131', 'Treadmill Drive Belt', 53, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-132', 'Weight Stack Pin', 12, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-133', 'Running Deck Lubricant', 67, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-134', 'Electronic Control Board', 70, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-135', 'Handlebar Foam Grip', 18, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-136', 'Display Console Overlay', 7, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-137', 'Safety Stop Key', 53, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-138', 'Bench Press Padding', 57, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-139', 'Display Console Overlay', 83, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-140', 'Elliptical Foot Pedal', 84, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-141', 'Bench Press Padding', 27, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-142', 'Bench Press Padding', 58, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-143', 'Treadmill Drive Belt', 23, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-144', 'Electronic Control Board', 70, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-145', 'Elliptical Foot Pedal', 67, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-146', 'Hydraulic Piston', 19, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-147', 'Heart Rate Sensor Grip', 15, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-148', 'Weight Stack Pin', 17, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-149', 'Electronic Control Board', 53, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-150', 'Bench Press Padding', 69, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-151', 'Resistance Adjustment Knob', 52, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-152', 'Strength Machine Cable (Steel)', 63, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-153', 'Display Console Overlay', 33, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-154', 'Safety Stop Key', 77, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-155', 'Stationary Bike Pedal Strap', 2, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-156', 'Rubber Dumbbell End Cap', 74, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-157', 'Battery for Cordless Machine', 31, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-158', 'Roller Bearing', 38, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-159', 'Bench Press Padding', 90, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-160', 'Handlebar Foam Grip', 15, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-161', 'Handlebar Foam Grip', 64, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-162', 'Bench Press Padding', 82, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-163', 'Stationary Bike Pedal Strap', 38, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-164', 'Resistance Adjustment Knob', 10, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-165', 'Safety Stop Key', 28, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-166', 'Treadmill Drive Belt', 11, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-167', 'Strength Machine Cable (Steel)', 51, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-168', 'Display Console Overlay', 58, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-169', 'Treadmill Drive Belt', 70, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-170', 'Running Deck Lubricant', 86, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-171', 'Resistance Adjustment Knob', 69, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-172', 'Weight Stack Pin', 88, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-173', 'Safety Stop Key', 23, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-174', 'Running Deck Lubricant', 47, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-175', 'Running Deck Lubricant', 27, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-176', 'Electronic Control Board', 23, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-177', 'Battery for Cordless Machine', 97, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-178', 'Heart Rate Sensor Grip', 77, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-179', 'Heart Rate Sensor Grip', 61, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-180', 'Battery for Cordless Machine', 24, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-181', 'Battery for Cordless Machine', 34, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-182', 'Pulley Wheel (Nylon)', 48, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-183', 'Pulley Wheel (Nylon)', 81, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-184', 'Stationary Bike Pedal Strap', 37, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-185', 'Stationary Bike Pedal Strap', 97, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-186', 'Stationary Bike Pedal Strap', 83, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-187', 'Roller Bearing', 68, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-188', 'Weight Stack Pin', 14, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-189', 'Handlebar Foam Grip', 79, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-190', 'Rubber Dumbbell End Cap', 51, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-191', 'Battery for Cordless Machine', 84, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-192', 'Display Console Overlay', 49, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-193', 'Hydraulic Piston', 49, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-194', 'Bench Press Padding', 4, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-195', 'Elliptical Foot Pedal', 11, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-196', 'Electronic Control Board', 14, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-197', 'Weight Stack Pin', 55, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-198', 'Elliptical Foot Pedal', 0, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-199', 'Resistance Adjustment Knob', 35, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-200', 'Rubber Dumbbell End Cap', 51, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-201', 'Treadmill Drive Belt', 22, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-202', 'Safety Stop Key', 38, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-203', 'Resistance Adjustment Knob', 41, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-204', 'Safety Stop Key', 80, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-205', 'Stationary Bike Pedal Strap', 56, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-206', 'Battery for Cordless Machine', 64, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-207', 'Treadmill Drive Belt', 84, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-208', 'Weight Stack Pin', 47, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-209', 'Weight Stack Pin', 48, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-210', 'Safety Stop Key', 68, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-211', 'Roller Bearing', 17, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-212', 'Roller Bearing', 34, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-213', 'Resistance Adjustment Knob', 31, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-214', 'Battery for Cordless Machine', 93, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-215', 'Hydraulic Piston', 53, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-216', 'Hydraulic Piston', 13, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-217', 'Battery for Cordless Machine', 77, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-218', 'Strength Machine Cable (Steel)', 59, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-219', 'Bench Press Padding', 69, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-220', 'Weight Stack Pin', 46, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-221', 'Stationary Bike Pedal Strap', 72, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-222', 'Treadmill Drive Belt', 27, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-223', 'Bench Press Padding', 83, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-224', 'Safety Stop Key', 70, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-225', 'Roller Bearing', 71, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-226', 'Pulley Wheel (Nylon)', 12, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-227', 'Strength Machine Cable (Steel)', 51, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-228', 'Roller Bearing', 12, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-229', 'Bench Press Padding', 91, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-230', 'Stationary Bike Pedal Strap', 57, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-231', 'Stationary Bike Pedal Strap', 97, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-232', 'Resistance Adjustment Knob', 39, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-233', 'Running Deck Lubricant', 37, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-234', 'Treadmill Drive Belt', 40, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-235', 'Electronic Control Board', 26, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-236', 'Hydraulic Piston', 50, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-237', 'Resistance Adjustment Knob', 8, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-238', 'Electronic Control Board', 94, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-239', 'Heart Rate Sensor Grip', 32, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-240', 'Handlebar Foam Grip', 74, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-241', 'Hydraulic Piston', 48, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-242', 'Roller Bearing', 34, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-243', 'Electronic Control Board', 26, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-244', 'Hydraulic Piston', 75, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-245', 'Resistance Adjustment Knob', 30, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-246', 'Roller Bearing', 23, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-247', 'Display Console Overlay', 84, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-248', 'Pulley Wheel (Nylon)', 8, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-249', 'Stationary Bike Pedal Strap', 75, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-250', 'Pulley Wheel (Nylon)', 9, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-251', 'Pulley Wheel (Nylon)', 74, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-252', 'Safety Stop Key', 69, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-253', 'Pulley Wheel (Nylon)', 76, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-254', 'Pulley Wheel (Nylon)', 31, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-255', 'Safety Stop Key', 32, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-256', 'Stationary Bike Pedal Strap', 60, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-257', 'Roller Bearing', 70, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-258', 'Safety Stop Key', 30, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-259', 'Elliptical Foot Pedal', 88, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-260', 'Safety Stop Key', 64, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-261', 'Treadmill Drive Belt', 4, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-262', 'Roller Bearing', 77, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-263', 'Heart Rate Sensor Grip', 52, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-264', 'Display Console Overlay', 93, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-265', 'Strength Machine Cable (Steel)', 83, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-266', 'Running Deck Lubricant', 65, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-267', 'Display Console Overlay', 1, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-268', 'Battery for Cordless Machine', 12, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-269', 'Hydraulic Piston', 20, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-270', 'Display Console Overlay', 77, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-271', 'Hydraulic Piston', 61, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-272', 'Weight Stack Pin', 25, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-273', 'Roller Bearing', 25, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-274', 'Hydraulic Piston', 25, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-275', 'Heart Rate Sensor Grip', 47, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-276', 'Display Console Overlay', 55, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-277', 'Running Deck Lubricant', 63, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-278', 'Handlebar Foam Grip', 91, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-279', 'Hydraulic Piston', 12, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-280', 'Display Console Overlay', 99, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-281', 'Safety Stop Key', 96, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-282', 'Stationary Bike Pedal Strap', 23, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-283', 'Hydraulic Piston', 62, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-284', 'Electronic Control Board', 85, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-285', 'Hydraulic Piston', 92, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-286', 'Weight Stack Pin', 100, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-287', 'Resistance Adjustment Knob', 58, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-288', 'Running Deck Lubricant', 69, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-289', 'Battery for Cordless Machine', 29, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-290', 'Rubber Dumbbell End Cap', 87, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-291', 'Running Deck Lubricant', 91, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-292', 'Stationary Bike Pedal Strap', 91, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-293', 'Battery for Cordless Machine', 94, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-294', 'Rubber Dumbbell End Cap', 41, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-295', 'Elliptical Foot Pedal', 14, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-296', 'Elliptical Foot Pedal', 19, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-297', 'Rubber Dumbbell End Cap', 97, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-298', 'Display Console Overlay', 86, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-299', 'Rubber Dumbbell End Cap', 79, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-300', 'Electronic Control Board', 85, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-301', 'Rubber Dumbbell End Cap', 58, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-302', 'Electronic Control Board', 85, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-303', 'Resistance Adjustment Knob', 67, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-304', 'Electronic Control Board', 16, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-305', 'Treadmill Drive Belt', 2, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-306', 'Weight Stack Pin', 9, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-307', 'Running Deck Lubricant', 1, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-308', 'Roller Bearing', 30, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-309', 'Handlebar Foam Grip', 75, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-310', 'Battery for Cordless Machine', 53, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-311', 'Pulley Wheel (Nylon)', 24, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-312', 'Battery for Cordless Machine', 86, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-313', 'Resistance Adjustment Knob', 2, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-314', 'Running Deck Lubricant', 5, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-315', 'Battery for Cordless Machine', 74, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-316', 'Resistance Adjustment Knob', 38, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-317', 'Weight Stack Pin', 39, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-318', 'Strength Machine Cable (Steel)', 39, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-319', 'Elliptical Foot Pedal', 23, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-320', 'Bench Press Padding', 47, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-321', 'Elliptical Foot Pedal', 29, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-322', 'Bench Press Padding', 76, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-323', 'Roller Bearing', 37, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-324', 'Resistance Adjustment Knob', 99, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-325', 'Treadmill Drive Belt', 74, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-326', 'Safety Stop Key', 86, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-327', 'Elliptical Foot Pedal', 10, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-328', 'Display Console Overlay', 89, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-329', 'Resistance Adjustment Knob', 78, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-330', 'Handlebar Foam Grip', 38, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-331', 'Battery for Cordless Machine', 66, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-332', 'Bench Press Padding', 63, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-333', 'Battery for Cordless Machine', 33, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-334', 'Heart Rate Sensor Grip', 68, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-335', 'Running Deck Lubricant', 71, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-336', 'Battery for Cordless Machine', 63, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-337', 'Hydraulic Piston', 60, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-338', 'Stationary Bike Pedal Strap', 85, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-339', 'Running Deck Lubricant', 28, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-340', 'Strength Machine Cable (Steel)', 13, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-341', 'Battery for Cordless Machine', 12, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-342', 'Elliptical Foot Pedal', 23, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-343', 'Display Console Overlay', 64, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-344', 'Handlebar Foam Grip', 63, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-345', 'Electronic Control Board', 63, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-346', 'Battery for Cordless Machine', 74, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-347', 'Weight Stack Pin', 1, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-348', 'Running Deck Lubricant', 100, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-349', 'Heart Rate Sensor Grip', 91, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-350', 'Safety Stop Key', 90, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-351', 'Display Console Overlay', 89, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-352', 'Running Deck Lubricant', 71, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-353', 'Elliptical Foot Pedal', 6, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-354', 'Hydraulic Piston', 78, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-355', 'Battery for Cordless Machine', 79, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-356', 'Display Console Overlay', 9, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-357', 'Resistance Adjustment Knob', 47, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-358', 'Roller Bearing', 76, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-359', 'Pulley Wheel (Nylon)', 88, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-360', 'Pulley Wheel (Nylon)', 8, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-361', 'Heart Rate Sensor Grip', 46, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-362', 'Elliptical Foot Pedal', 89, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-363', 'Heart Rate Sensor Grip', 3, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-364', 'Strength Machine Cable (Steel)', 67, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-365', 'Elliptical Foot Pedal', 62, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-366', 'Rubber Dumbbell End Cap', 48, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-367', 'Rubber Dumbbell End Cap', 34, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-368', 'Battery for Cordless Machine', 55, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-369', 'Weight Stack Pin', 86, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-370', 'Rubber Dumbbell End Cap', 83, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-371', 'Electronic Control Board', 21, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-372', 'Hydraulic Piston', 49, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-373', 'Weight Stack Pin', 89, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-374', 'Battery for Cordless Machine', 43, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-375', 'Treadmill Drive Belt', 38, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-376', 'Hydraulic Piston', 1, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-377', 'Rubber Dumbbell End Cap', 36, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-378', 'Resistance Adjustment Knob', 97, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-379', 'Treadmill Drive Belt', 25, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-380', 'Display Console Overlay', 50, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-381', 'Safety Stop Key', 4, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-382', 'Heart Rate Sensor Grip', 68, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-383', 'Hydraulic Piston', 41, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-384', 'Elliptical Foot Pedal', 56, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-385', 'Safety Stop Key', 98, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-386', 'Weight Stack Pin', 71, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-387', 'Bench Press Padding', 15, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-388', 'Pulley Wheel (Nylon)', 14, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-389', 'Resistance Adjustment Knob', 36, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-390', 'Resistance Adjustment Knob', 26, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-391', 'Display Console Overlay', 60, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-392', 'Roller Bearing', 81, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-393', 'Hydraulic Piston', 62, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-394', 'Rubber Dumbbell End Cap', 93, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-395', 'Bench Press Padding', 47, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-396', 'Elliptical Foot Pedal', 42, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-397', 'Elliptical Foot Pedal', 65, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-398', 'Pulley Wheel (Nylon)', 7, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-399', 'Weight Stack Pin', 86, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-400', 'Resistance Adjustment Knob', 27, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-401', 'Bench Press Padding', 63, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-402', 'Running Deck Lubricant', 25, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-403', 'Strength Machine Cable (Steel)', 46, 10);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-404', 'Running Deck Lubricant', 49, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-405', 'Rubber Dumbbell End Cap', 8, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-406', 'Running Deck Lubricant', 33, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-407', 'Hydraulic Piston', 52, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-408', 'Rubber Dumbbell End Cap', 91, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-409', 'Elliptical Foot Pedal', 6, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-410', 'Resistance Adjustment Knob', 59, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-411', 'Roller Bearing', 30, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-412', 'Rubber Dumbbell End Cap', 79, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-413', 'Treadmill Drive Belt', 60, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-414', 'Electronic Control Board', 45, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-415', 'Stationary Bike Pedal Strap', 12, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-416', 'Rubber Dumbbell End Cap', 82, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-417', 'Weight Stack Pin', 26, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-418', 'Roller Bearing', 25, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-419', 'Battery for Cordless Machine', 11, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-420', 'Bench Press Padding', 75, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-421', 'Safety Stop Key', 70, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-422', 'Rubber Dumbbell End Cap', 65, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-423', 'Battery for Cordless Machine', 90, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-424', 'Resistance Adjustment Knob', 65, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-425', 'Heart Rate Sensor Grip', 16, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-426', 'Running Deck Lubricant', 11, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-427', 'Stationary Bike Pedal Strap', 65, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-428', 'Battery for Cordless Machine', 76, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-429', 'Pulley Wheel (Nylon)', 44, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-430', 'Heart Rate Sensor Grip', 99, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-431', 'Resistance Adjustment Knob', 93, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-432', 'Electronic Control Board', 34, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-433', 'Battery for Cordless Machine', 34, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-434', 'Weight Stack Pin', 25, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-435', 'Battery for Cordless Machine', 2, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-436', 'Roller Bearing', 35, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-437', 'Bench Press Padding', 1, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-438', 'Safety Stop Key', 7, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-439', 'Battery for Cordless Machine', 78, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-440', 'Safety Stop Key', 5, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-441', 'Stationary Bike Pedal Strap', 91, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-442', 'Stationary Bike Pedal Strap', 60, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-443', 'Bench Press Padding', 31, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-444', 'Safety Stop Key', 43, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-445', 'Pulley Wheel (Nylon)', 52, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-446', 'Rubber Dumbbell End Cap', 85, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-447', 'Bench Press Padding', 87, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-448', 'Display Console Overlay', 15, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-449', 'Handlebar Foam Grip', 18, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-450', 'Stationary Bike Pedal Strap', 29, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-451', 'Resistance Adjustment Knob', 77, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-452', 'Roller Bearing', 53, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-453', 'Running Deck Lubricant', 14, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-454', 'Strength Machine Cable (Steel)', 91, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-455', 'Electronic Control Board', 29, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-456', 'Treadmill Drive Belt', 64, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-457', 'Pulley Wheel (Nylon)', 66, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-458', 'Bench Press Padding', 58, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-459', 'Strength Machine Cable (Steel)', 36, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-460', 'Running Deck Lubricant', 35, 19);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-461', 'Safety Stop Key', 90, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-462', 'Weight Stack Pin', 80, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-463', 'Strength Machine Cable (Steel)', 41, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-464', 'Hydraulic Piston', 65, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-465', 'Resistance Adjustment Knob', 88, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-466', 'Roller Bearing', 2, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-467', 'Roller Bearing', 100, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-468', 'Handlebar Foam Grip', 28, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-469', 'Resistance Adjustment Knob', 82, 9);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-470', 'Stationary Bike Pedal Strap', 54, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-471', 'Handlebar Foam Grip', 57, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-472', 'Heart Rate Sensor Grip', 64, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-473', 'Roller Bearing', 31, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-474', 'Roller Bearing', 74, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-475', 'Heart Rate Sensor Grip', 5, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-476', 'Hydraulic Piston', 92, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-477', 'Elliptical Foot Pedal', 31, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-478', 'Resistance Adjustment Knob', 10, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-479', 'Heart Rate Sensor Grip', 59, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-480', 'Safety Stop Key', 92, 6);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-481', 'Weight Stack Pin', 73, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-482', 'Stationary Bike Pedal Strap', 55, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-483', 'Battery for Cordless Machine', 68, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-484', 'Resistance Adjustment Knob', 52, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-485', 'Battery for Cordless Machine', 36, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-486', 'Electronic Control Board', 70, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-487', 'Battery for Cordless Machine', 92, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-488', 'Treadmill Drive Belt', 46, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-489', 'Battery for Cordless Machine', 15, 8);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-490', 'Battery for Cordless Machine', 15, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-491', 'Rubber Dumbbell End Cap', 60, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-492', 'Running Deck Lubricant', 39, 17);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-493', 'Rubber Dumbbell End Cap', 55, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-494', 'Strength Machine Cable (Steel)', 76, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-495', 'Rubber Dumbbell End Cap', 93, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-496', 'Treadmill Drive Belt', 22, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-497', 'Strength Machine Cable (Steel)', 92, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-498', 'Rubber Dumbbell End Cap', 28, 5);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-499', 'Battery for Cordless Machine', 81, 7);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-500', 'Hydraulic Piston', 14, 15);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-501', 'Safety Stop Key', 25, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-502', 'Running Deck Lubricant', 43, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-503', 'Rubber Dumbbell End Cap', 95, 16);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-504', 'Electronic Control Board', 78, 11);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-505', 'Rubber Dumbbell End Cap', 59, 13);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-506', 'Rubber Dumbbell End Cap', 21, 18);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-507', 'Handlebar Foam Grip', 69, 14);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-508', 'Electronic Control Board', 84, 20);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-509', 'Strength Machine Cable (Steel)', 89, 12);
insert into SPARE_PART (Part_Number, Part_Description, Stock_Quantity, Reorder_Level) values ('P-510', 'Treadmill Drive Belt', 41, 11);
